config/routes.rb
Rails.application.routes.draw do
  root 'fizz_buzzs#index'

  resources :jobs, only: [:index, :show] do
    member do
      get :poll
    end
  end

  resources :fizz_buzzs do
    member do
      get :increment
    end
    collection do
      get :generate
      get :increment_all
    end
  end

  resources :queues, only: [:index, :show]

end

app/models/fizz_buzz.rb
class FizzBuzz < ActiveRecord::Base

  def self.generate(name = nil, fizz_freq = nil, buzz_freq = nil)
    name ||= FizzBuzz.maximum(:name)
    name ||= 'fizzbuzz-001'
    name.succ! while FizzBuzz.where(name: name).exists?

    fizz_freq ||= rand(5) + 1
    buzz_freq ||= rand(5) + 1
    self.create!(
      name: name,
      fizz: 0,
      buzz: 0,
      fizz_frequency: fizz_freq,
      buzz_frequency: buzz_freq
    )
  end

  def increment!
    self.fizz += 1
    self.buzz += 1
    save!
  end

  def should_fizz?
    (self.fizz % self.fizz_frequency) == 0
  end

  def should_buzz?
    (self.buzz % self.buzz_frequency) == 0
  end

  def result
    "#{'fizz' if should_fizz?}#{'buzz' if should_buzz?}"
  end

end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :job_messages

  serialize :args

  PENDING = 'pending'
  RUNNING = 'running'
  FINISHED = 'finished'
  ERROR = 'error'

  def messages(last_message=nil)
    job_messages.reload
    if last_message
      job_messages.where("order_no > #{last_message}").order(:order_no).map(&:formatted_message)
    else
      job_messages.order(:order_no).map(&:formatted_message)
    end
  end

  def add_message(msg)
    @order_no ||= job_messages.map(&:order_no).max || 0
    job_messages.create(message: msg, order_no: @order_no += 1)
  end

end

app/models/job_message.rb
class JobMessage < ActiveRecord::Base

  belongs_to :job

  def formatted_message
    "[#{created_at.strftime('%H:%M:%S')}] #{message}"
  end

end

app/models/job_schedule.rb
class JobSchedule < ActiveRecord::Base

  serialize :parameters

  def self.generate
    #if JobSchedule.count == 0
      JobSchedule.create!(
        name: '1 minute FizzBuzz',
        frequency_value: 1,
        frequency_unit: 'minute',
        class_name: 'FizzBuzzJob',
        queue_name: 'default',
        parameters: {}
      )
    #end
  end

  def run
    class_name.constantize.perform_later(parameters)
  end

  def frequency
    frequency_value.to_f.send(frequency_unit.to_s.pluralize)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fizz_buzzs_controller.rb
class FizzBuzzsController < ApplicationController
  before_action :set_fizz_buzz, only: [:show, :edit, :update, :destroy, :increment]

  def index
    @fizz_buzzs = FizzBuzz.all
  end

  def show
  end

  def new
    @fizz_buzz = FizzBuzz.new
  end

  def edit
  end

  def create
    @fizz_buzz = FizzBuzz.new(fizz_buzz_params)

    respond_to do |format|
      if @fizz_buzz.save
        format.html { redirect_to @fizz_buzz, notice: 'Fizz buzz was successfully created.' }
        format.json { render :show, status: :created, location: @fizz_buzz }
      else
        format.html { render :new }
        format.json { render json: @fizz_buzz.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fizz_buzz.update(fizz_buzz_params)
        format.html { redirect_to @fizz_buzz, notice: 'Fizz buzz was successfully updated.' }
        format.json { render :show, status: :ok, location: @fizz_buzz }
      else
        format.html { render :edit }
        format.json { render json: @fizz_buzz.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fizz_buzz.destroy
    respond_to do |format|
      format.html { redirect_to fizz_buzzs_url, notice: 'Fizz buzz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def increment
    process = FizzBuzzJob.perform_later(fizz_buzz_ids: [@fizz_buzz.id])
    redirect_to(job_path(process.job))
  end

  def increment_all
    process = FizzBuzzJob.perform_later()
    redirect_to(job_path(process.job))
  end
  
  def generate
    fizz_buzz = FizzBuzz.generate
    redirect_to fizz_buzz_path(fizz_buzz)
  end

  private
    def set_fizz_buzz
      @fizz_buzz = FizzBuzz.find(params[:id])
    end

    def fizz_buzz_params
      params.require(:fizz_buzz).permit(:name, :fizz, :buzz, :fizz_frequency, :integer, :buzz_frequency)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  #TODO
  def index
    @jobs = Job.order('created_at desc').limit(50)
  end

  def show
    @job = Job.find(params[:id])
  end

  def poll
    job = Job.find(params[:id])
    messages = job.messages(params[:last_message])
    render json: {
      messages: messages,
      time: Time.now.to_s,
      status: job.status,
      last_message: job.job_messages.map(&:order_no).max
    }
  end

end

app/controllers/queues_controller.rb
class QueuesController < ApplicationController

  def index
    @queues = Sidekiq::Queue.all
  end

  def show
    @queue = Sidekiq::Queue.new(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fizz_buzzs_helper.rb
module FizzBuzzsHelper
end

app/views/fizz_buzzs/_form.html.erb
<%= form_for(@fizz_buzz) do |f| %>
  <% if @fizz_buzz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fizz_buzz.errors.count, "error") %> prohibited this fizz_buzz from being saved:</h2>

      <ul>
      <% @fizz_buzz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fizz %><br>
    <%= f.number_field :fizz %>
  </div>
  <div class="field">
    <%= f.label :buzz %><br>
    <%= f.number_field :buzz %>
  </div>
  <div class="field">
    <%= f.label :fizz_frequency %><br>
    <%= f.text_field :fizz_frequency %>
  </div>
  <div class="field">
    <%= f.label :buzz_frequency %><br>
    <%= f.number_field :buzz_frequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fizz_buzzs/edit.html.erb
<h1>Editing Fizz Buzz</h1>

<%= render 'form' %>

<%= link_to 'Show', @fizz_buzz %> |
<%= link_to 'Back', fizz_buzzs_path %>

app/views/fizz_buzzs/increment.html.erb
<h1>Incrementing <%= @fizz_buzz.name %></h1>

<h1><%= @fizz_buzz.result %></h1>
<h1><%= @fizz_buzz.result %></h1>
<h1><%= @fizz_buzz.result %></h1>


<%= link_to 'Back', fizz_buzz_path(@fizz_buzz) %>

app/views/fizz_buzzs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fizz Buzzs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fizz</th>
      <th>Buzz</th>
      <th>Fizz frequency</th>
      <th>Buzz frequency</th>
      <th>Result</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @fizz_buzzs.each do |fizz_buzz| %>
      <tr>
        <td><%= fizz_buzz.name %></td>
        <td><%= fizz_buzz.fizz %></td>
        <td><%= fizz_buzz.buzz %></td>
        <td><%= fizz_buzz.fizz_frequency %></td>
        <td><%= fizz_buzz.buzz_frequency %></td>
        <td><%= fizz_buzz.result %></td>
        <td><%= link_to 'Show', fizz_buzz %></td>
        <td><%= link_to 'Edit', edit_fizz_buzz_path(fizz_buzz) %></td>
        <td><%= link_to 'Increment', increment_fizz_buzz_path(fizz_buzz) %></td>
        <td><%= link_to 'Destroy', fizz_buzz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fizz buzz', new_fizz_buzz_path %>
<%= link_to 'Generate Fizz buzz', generate_fizz_buzzs_path %>
<%= link_to 'Increment All', increment_all_fizz_buzzs_path %>

app/views/fizz_buzzs/new.html.erb
<h1>New Fizz Buzz</h1>

<%= render 'form' %>

<%= link_to 'Back', fizz_buzzs_path %>

app/views/fizz_buzzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fizz_buzz.name %>
</p>

<p>
  <strong>Fizz:</strong>
  <%= @fizz_buzz.fizz %>
</p>

<p>
  <strong>Buzz:</strong>
  <%= @fizz_buzz.buzz %>
</p>

<p>
  <strong>Fizz frequency:</strong>
  <%= @fizz_buzz.fizz_frequency %>
</p>

<p>
  <strong>Buzz frequency:</strong>
  <%= @fizz_buzz.buzz_frequency %>
</p>

<h1><%= @fizz_buzz.result %></h1>

<%= link_to 'Edit', edit_fizz_buzz_path(@fizz_buzz) %> |
<%= link_to 'Increment', increment_fizz_buzz_path(@fizz_buzz) %> |
<%= link_to 'Back', fizz_buzzs_path %>

app/views/jobs/index.html.erb
<h1>Current Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Created At</th>
      <th>Class</th>
      <th>Arguments</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to(job.created_at, job_path(job)) %></td>
        <td><%= job.job_class %></td>
        <td><%= job.args.inspect %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/show.html.erb
<h1>Job: <%= @job.job_class %></h1>

<dl>
  <dt>Job Class</dt>
  <dd><%= @job.job_class %></dd>
  <dt>Arguments</dt>
  <dd><%= @job.args.inspect %></dd>
  <dt>Status</dt>
  <dd id="status"><%= @job.status %></dd>
</dl>

<h2>Messages</h2>

<p id="indicator"></p>
<ul id="messages" data-job_id="<%= @job.id %>">

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <ul>
      <li><%= link_to 'Fizz Buzzes', fizz_buzzs_path %></li>
      <li><%= link_to 'Queues', queues_path %></li>
      <li><%= link_to 'Jobs', jobs_path %></li>
    </ul>
  </div>

<%= yield %>

</body>
</html>

app/views/queues/index.html.erb
<h1>Sidekiq Queues</h1>

<table>
  <thead>
    <tr>
      <th>Queue Name</th>
      <th>Size</th>
    </tr>
  </thead>
  <tbody>
    <% @queues.each do |queue| %>
      <tr>
        <td><%= link_to queue.name, queue_path(queue.name) %></td>
        <td><%= queue.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Working Jobs</h1>

<h2>Currently working</h2>
<table>
  <thead>
    <tr>
      <th>Process ID</th>
      <th>Thread ID</th>
      <th>Queue</th>
      <th>Run At</th>
      <th>Job Class</th>
      <th>Arguments</th>
    </tr>
  </thead>
  <tbody>
    <% Sidekiq::Workers.new.each do |process_id, thread_id, work| %>
      <tr>
        <td><%= process_id %></td>
        <td><%= thread_id %></td>
        <td><%= work['queue'] %></td>
        <td><%= work['run_at'] %></td>
        <td><%= work['payload']['wrapped'] %></td>
        <td><%= work['payload']['args'][0]['arguments'].inspect %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/queues/show.html.erb
<h1>Queue: <%= @queue.name %></h1>

<h2>Queued Jobs</h2>

<table>
  <thead>
    <tr>
      <th>Job ID</th>
      <th>Class</th>
      <th>Arguments</th>
    </tr>
  </thead>
  <tbody>
    <% @queue.each do |job| %>
      <tr>
        <td><%= job.jid %></td>
        <td><%= job.args[0]['job_class'] %></td>
        <td><%= job.args[0]['arguments'].inspect %></td>
      </tr>
    <% end %>
  </tbody>
</table>